[[constraint]]
  name = "github.com/confluentinc/confluent-kafka-go"
  version = "0.11.4"

[[constraint]]
  name = "github.com/nu7hatch/gouuid"

[[constraint]]
  name = "github.com/radovskyb/watcher"
  version = "1.0.2"
