/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type AlgoOutputModel struct {

	Id int32 `json:"id,omitempty"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	OutputDeliveryType string `json:"outputDeliveryType,omitempty"`

	Parameter string `json:"parameter,omitempty"`

	MediaType *MediaTypeModel `json:"mediaType"`

	CreatedTimestamp time.Time `json:"createdTimestamp,omitempty"`

	UpdatedTimestamp time.Time `json:"updatedTimestamp,omitempty"`
}
