/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type DataTypeModel struct {

	Name string `json:"name"`

	Regex string `json:"regex,omitempty"`

	Precision int32 `json:"precision,omitempty"`

	Scale int32 `json:"scale,omitempty"`

	CreatedTimestamp time.Time `json:"createdTimestamp,omitempty"`

	UpdatedTimestamp time.Time `json:"updatedTimestamp,omitempty"`
}
