/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FileReference struct {

	ServerAlias string `json:"serverAlias,omitempty"`

	Bucket string `json:"bucket,omitempty"`

	File string `json:"file,omitempty"`
}
