/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LogMessage struct {
	LogMessageType string `json:"logMessageType,omitempty"`

	LogSource string `json:"logSource,omitempty"`

	EndpointOwnerUserName string `json:"endpointOwnerUserName,omitempty"`

	EndpointName string `json:"endpointName,omitempty"`

	AlgoOwnerUserName string `json:"algoOwnerUserName,omitempty"`

	AlgoName string `json:"algoName,omitempty"`

	AlgoVersionTag string `json:"algoVersionTag,omitempty"`

	AlgoIndex int32 `json:"sourceAlgoIndex,omitempty"`

	Status string `json:"status,omitempty"`

	CompletionPercent float64 `json:"completionPercent,omitempty"`

	RuntimeMs int64 `json:"runtimeMs,omitempty"`

	Log string `json:"log,omitempty"`
}
