/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type LogEntryModel struct {

	Level string `json:"level,omitempty"`

	Type_ string `json:"type,omitempty"`

	Ts time.Time `json:"ts,omitempty"`

	Status string `json:"status,omitempty"`

	RunId string `json:"runId,omitempty"`

	IsError bool `json:"isError,omitempty"`

	Msg string `json:"msg,omitempty"`

	Version string `json:"version,omitempty"`

	Data map[string]interface{} `json:"data,omitempty"`
}
