/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type PipelineRouteModel struct {

	RouteType string `json:"routeType,omitempty"`

	PipelineEndpointSourceOutputName string `json:"pipelineEndpointSourceOutputName,omitempty"`

	PipelineDataSourceId int32 `json:"pipelineDataSourceId,omitempty"`

	PipelineDataSource *PipelineDataConnectorModel `json:"pipelineDataSource,omitempty"`

	PipelineDataSourceIndex int32 `json:"pipelineDataSourceIndex,omitempty"`

	SourceAlgoOwnerName string `json:"sourceAlgoOwnerName,omitempty"`

	SourceAlgoUrlName string `json:"sourceAlgoUrlName,omitempty"`

	SourceAlgoIndex int32 `json:"sourceAlgoIndex,omitempty"`

	SourceAlgoOutputId int32 `json:"sourceAlgoOutputId,omitempty"`

	SourceAlgoOutput *AlgoOutputModel `json:"sourceAlgoOutput,omitempty"`

	PipelineDataSinkId int32 `json:"pipelineDataSinkId,omitempty"`

	PipelineDataSink *PipelineDataConnectorModel `json:"pipelineDataSink,omitempty"`

	PipelineDataSinkIndex int32 `json:"pipelineDataSinkIndex,omitempty"`

	DestAlgoOwnerName string `json:"destAlgoOwnerName,omitempty"`

	DestAlgoUrlName string `json:"destAlgoUrlName,omitempty"`

	DestAlgoIndex int32 `json:"destAlgoIndex,omitempty"`

	DestAlgoInputId int32 `json:"destAlgoInputId,omitempty"`

	DestAlgoInput *AlgoInputModel `json:"destAlgoInput,omitempty"`

	CreatedTimestamp time.Time `json:"createdTimestamp,omitempty"`

	UpdatedTimestamp time.Time `json:"updatedTimestamp,omitempty"`
}
