/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RunnerConfig struct {
	EndpointOwnerUserName string `json:"endpointOwnerUserName,omitempty"`

	EndpointUrlName string `json:"endpointUrlName,omitempty"`

	PipelineOwnerUserName string `json:"pipelineOwnerUserName,omitempty"`

	PipelineUrlName string `json:"pipelineUrlName,omitempty"`

	AlgoOwnerUserName string `json:"algoOwnerUserName,omitempty"`

	AlgoUrlName string `json:"algoUrlName,omitempty"`

	AlgoVersionTag string `json:"algoVersionTag,omitempty"`

	Entrypoint string `json:"entrypoint,omitempty"`

	ServerType string `json:"serverType,omitempty"`

	AlgoParams []AlgoParamModel `json:"algoParams,omitempty"`

	WriteAllOutputs bool `json:"writeAllOutputs,omitempty"`

	Outputs []AlgoOutputModel `json:"outputs,omitempty"`

	PipelineRoutes []PipelineRouteModel `json:"pipelineRoutes,omitempty"`

	GpuEnabled bool `json:"gpuEnabled,omitempty"`

	TimeoutSeconds int32 `json:"timeoutSeconds,omitempty"`
}
