/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MetricSourceTypes the model 'MetricSourceTypes'
type MetricSourceTypes string

// List of MetricSourceTypes
const (
	METRICSOURCETYPES_RESOURCE MetricSourceTypes = "Resource"
	METRICSOURCETYPES_OBJECT MetricSourceTypes = "Object"
	METRICSOURCETYPES_PODS MetricSourceTypes = "Pods"
	METRICSOURCETYPES_EXTERNAL MetricSourceTypes = "External"
)
