/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// LogEntryModel struct for LogEntryModel
type LogEntryModel struct {
	Version string `json:"version,omitempty"`
	Level *LogLevels `json:"level,omitempty"`
	Type *LogTypes `json:"type,omitempty"`
	Caller string `json:"caller,omitempty"`
	Logger string `json:"logger,omitempty"`
	Ts time.Time `json:"ts,omitempty"`
	TraceId string `json:"traceId,omitempty"`
	Msg string `json:"msg"`
	IsError bool `json:"isError,omitempty"`
	Error string `json:"error"`
	Data *map[string]interface{} `json:"data,omitempty"`
}
